# Chỉ định theme
remote_theme: pmarsceill/just-the-docs

# Bật plugin remote theme
plugins:
  - jekyll-remote-theme

# Tiêu đề site
title: "Duplication Text Report"

# Nếu muốn nút View on GitHub dẫn tới repo khác
github: "BTL-DSA-HK251/BTL-Extended-DSA"

# Layout mặc định cho pages
# Just the Docs hỗ trợ layout 'default', 'home', 'minimal'
# Dùng minimal để gọn, full-width
just_the_docs:
  homepage_layout: minimal
